// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.26.1
// source: twit.proto

package twit

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TwitRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TwitId    string `protobuf:"bytes,2,opt,name=twit_id,json=twitId,proto3" json:"twit_id,omitempty"`
	Content   string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ImageUrl  string `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Id        string `protobuf:"bytes,5,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt string `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Likes     int32  `protobuf:"varint,7,opt,name=likes,proto3" json:"likes,omitempty"`
}

func (x *TwitRes) Reset() {
	*x = TwitRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_twit_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TwitRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwitRes) ProtoMessage() {}

func (x *TwitRes) ProtoReflect() protoreflect.Message {
	mi := &file_twit_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwitRes.ProtoReflect.Descriptor instead.
func (*TwitRes) Descriptor() ([]byte, []int) {
	return file_twit_proto_rawDescGZIP(), []int{0}
}

func (x *TwitRes) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TwitRes) GetTwitId() string {
	if x != nil {
		return x.TwitId
	}
	return ""
}

func (x *TwitRes) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TwitRes) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *TwitRes) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TwitRes) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *TwitRes) GetLikes() int32 {
	if x != nil {
		return x.Likes
	}
	return 0
}

type TwitCreateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TwitId   string `protobuf:"bytes,2,opt,name=twit_id,json=twitId,proto3" json:"twit_id,omitempty"`
	Content  string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ImageUrl string `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
}

func (x *TwitCreateReq) Reset() {
	*x = TwitCreateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_twit_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TwitCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwitCreateReq) ProtoMessage() {}

func (x *TwitCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_twit_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwitCreateReq.ProtoReflect.Descriptor instead.
func (*TwitCreateReq) Descriptor() ([]byte, []int) {
	return file_twit_proto_rawDescGZIP(), []int{1}
}

func (x *TwitCreateReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TwitCreateReq) GetTwitId() string {
	if x != nil {
		return x.TwitId
	}
	return ""
}

func (x *TwitCreateReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TwitCreateReq) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type TwitGetAllReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  string  `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TwitId  string  `protobuf:"bytes,2,opt,name=twit_id,json=twitId,proto3" json:"twit_id,omitempty"`
	Content string  `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Filter  *Filter `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
}

func (x *TwitGetAllReq) Reset() {
	*x = TwitGetAllReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_twit_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TwitGetAllReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwitGetAllReq) ProtoMessage() {}

func (x *TwitGetAllReq) ProtoReflect() protoreflect.Message {
	mi := &file_twit_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwitGetAllReq.ProtoReflect.Descriptor instead.
func (*TwitGetAllReq) Descriptor() ([]byte, []int) {
	return file_twit_proto_rawDescGZIP(), []int{2}
}

func (x *TwitGetAllReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TwitGetAllReq) GetTwitId() string {
	if x != nil {
		return x.TwitId
	}
	return ""
}

func (x *TwitGetAllReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TwitGetAllReq) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type TwitGetAllRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Twits []*TwitRes `protobuf:"bytes,1,rep,name=twits,proto3" json:"twits,omitempty"`
	Count int32      `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *TwitGetAllRes) Reset() {
	*x = TwitGetAllRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_twit_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TwitGetAllRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwitGetAllRes) ProtoMessage() {}

func (x *TwitGetAllRes) ProtoReflect() protoreflect.Message {
	mi := &file_twit_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwitGetAllRes.ProtoReflect.Descriptor instead.
func (*TwitGetAllRes) Descriptor() ([]byte, []int) {
	return file_twit_proto_rawDescGZIP(), []int{3}
}

func (x *TwitGetAllRes) GetTwits() []*TwitRes {
	if x != nil {
		return x.Twits
	}
	return nil
}

func (x *TwitGetAllRes) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type TwitUpdateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId   string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content  string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ImageUrl string `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
}

func (x *TwitUpdateReq) Reset() {
	*x = TwitUpdateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_twit_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TwitUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwitUpdateReq) ProtoMessage() {}

func (x *TwitUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_twit_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwitUpdateReq.ProtoReflect.Descriptor instead.
func (*TwitUpdateReq) Descriptor() ([]byte, []int) {
	return file_twit_proto_rawDescGZIP(), []int{4}
}

func (x *TwitUpdateReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TwitUpdateReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TwitUpdateReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TwitUpdateReq) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type TwitDeleteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *TwitDeleteReq) Reset() {
	*x = TwitDeleteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_twit_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TwitDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwitDeleteReq) ProtoMessage() {}

func (x *TwitDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_twit_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwitDeleteReq.ProtoReflect.Descriptor instead.
func (*TwitDeleteReq) Descriptor() ([]byte, []int) {
	return file_twit_proto_rawDescGZIP(), []int{5}
}

func (x *TwitDeleteReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TwitDeleteReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_twit_proto protoreflect.FileDescriptor

var file_twit_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x74, 0x77, 0x69, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x74, 0x77,
	0x69, 0x74, 0x1a, 0x0d, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x32, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xb7, 0x01, 0x0a, 0x07, 0x54, 0x77, 0x69, 0x74, 0x52, 0x65, 0x73, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x77, 0x69, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x77, 0x69, 0x74, 0x49, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x22, 0x78, 0x0a, 0x0d, 0x54,
	0x77, 0x69, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x77, 0x69, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x77, 0x69, 0x74, 0x49, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x55, 0x72, 0x6c, 0x22, 0x81, 0x01, 0x0a, 0x0d, 0x54, 0x77, 0x69, 0x74, 0x47, 0x65,
	0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x17, 0x0a, 0x07, 0x74, 0x77, 0x69, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x74, 0x77, 0x69, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x12, 0x24, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x74, 0x77, 0x69, 0x74, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0x4a, 0x0a, 0x0d, 0x54, 0x77, 0x69,
	0x74, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x12, 0x23, 0x0a, 0x05, 0x74, 0x77,
	0x69, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x74, 0x77, 0x69, 0x74,
	0x2e, 0x54, 0x77, 0x69, 0x74, 0x52, 0x65, 0x73, 0x52, 0x05, 0x74, 0x77, 0x69, 0x74, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x6f, 0x0a, 0x0d, 0x54, 0x77, 0x69, 0x74, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x22, 0x38, 0x0a, 0x0d, 0x54, 0x77, 0x69, 0x74, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x32, 0xe8, 0x01, 0x0a, 0x0b, 0x54, 0x77, 0x69, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x29, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x13, 0x2e, 0x74, 0x77, 0x69,
	0x74, 0x2e, 0x54, 0x77, 0x69, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a,
	0x0a, 0x2e, 0x74, 0x77, 0x69, 0x74, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x12, 0x24, 0x0a, 0x07, 0x47,
	0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x12, 0x0a, 0x2e, 0x74, 0x77, 0x69, 0x74, 0x2e, 0x42, 0x79,
	0x49, 0x64, 0x1a, 0x0d, 0x2e, 0x74, 0x77, 0x69, 0x74, 0x2e, 0x54, 0x77, 0x69, 0x74, 0x52, 0x65,
	0x73, 0x12, 0x32, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x12, 0x13, 0x2e, 0x74, 0x77,
	0x69, 0x74, 0x2e, 0x54, 0x77, 0x69, 0x74, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71,
	0x1a, 0x13, 0x2e, 0x74, 0x77, 0x69, 0x74, 0x2e, 0x54, 0x77, 0x69, 0x74, 0x47, 0x65, 0x74, 0x41,
	0x6c, 0x6c, 0x52, 0x65, 0x73, 0x12, 0x29, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12,
	0x13, 0x2e, 0x74, 0x77, 0x69, 0x74, 0x2e, 0x54, 0x77, 0x69, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x1a, 0x0a, 0x2e, 0x74, 0x77, 0x69, 0x74, 0x2e, 0x56, 0x6f, 0x69, 0x64,
	0x12, 0x29, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x13, 0x2e, 0x74, 0x77, 0x69,
	0x74, 0x2e, 0x54, 0x77, 0x69, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a,
	0x0a, 0x2e, 0x74, 0x77, 0x69, 0x74, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x42, 0x0f, 0x5a, 0x0d, 0x67,
	0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x77, 0x69, 0x74, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_twit_proto_rawDescOnce sync.Once
	file_twit_proto_rawDescData = file_twit_proto_rawDesc
)

func file_twit_proto_rawDescGZIP() []byte {
	file_twit_proto_rawDescOnce.Do(func() {
		file_twit_proto_rawDescData = protoimpl.X.CompressGZIP(file_twit_proto_rawDescData)
	})
	return file_twit_proto_rawDescData
}

var file_twit_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_twit_proto_goTypes = []interface{}{
	(*TwitRes)(nil),       // 0: twit.TwitRes
	(*TwitCreateReq)(nil), // 1: twit.TwitCreateReq
	(*TwitGetAllReq)(nil), // 2: twit.TwitGetAllReq
	(*TwitGetAllRes)(nil), // 3: twit.TwitGetAllRes
	(*TwitUpdateReq)(nil), // 4: twit.TwitUpdateReq
	(*TwitDeleteReq)(nil), // 5: twit.TwitDeleteReq
	(*Filter)(nil),        // 6: twit.Filter
	(*ById)(nil),          // 7: twit.ById
	(*Void)(nil),          // 8: twit.Void
}
var file_twit_proto_depIdxs = []int32{
	6, // 0: twit.TwitGetAllReq.filter:type_name -> twit.Filter
	0, // 1: twit.TwitGetAllRes.twits:type_name -> twit.TwitRes
	1, // 2: twit.TwitService.Create:input_type -> twit.TwitCreateReq
	7, // 3: twit.TwitService.GetById:input_type -> twit.ById
	2, // 4: twit.TwitService.GetAll:input_type -> twit.TwitGetAllReq
	4, // 5: twit.TwitService.Update:input_type -> twit.TwitUpdateReq
	5, // 6: twit.TwitService.Delete:input_type -> twit.TwitDeleteReq
	8, // 7: twit.TwitService.Create:output_type -> twit.Void
	0, // 8: twit.TwitService.GetById:output_type -> twit.TwitRes
	3, // 9: twit.TwitService.GetAll:output_type -> twit.TwitGetAllRes
	8, // 10: twit.TwitService.Update:output_type -> twit.Void
	8, // 11: twit.TwitService.Delete:output_type -> twit.Void
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_twit_proto_init() }
func file_twit_proto_init() {
	if File_twit_proto != nil {
		return
	}
	file_common2_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_twit_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TwitRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_twit_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TwitCreateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_twit_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TwitGetAllReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_twit_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TwitGetAllRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_twit_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TwitUpdateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_twit_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TwitDeleteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_twit_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_twit_proto_goTypes,
		DependencyIndexes: file_twit_proto_depIdxs,
		MessageInfos:      file_twit_proto_msgTypes,
	}.Build()
	File_twit_proto = out.File
	file_twit_proto_rawDesc = nil
	file_twit_proto_goTypes = nil
	file_twit_proto_depIdxs = nil
}
